scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.doorClosedEast, function (sprite, location) {
    tiles.setTilemap(tilemap`level3`)
})
function next_level () {
	
}
scene.onOverlapTile(SpriteKind.Player, sprites.builtin.forestTiles9, function (sprite, location) {
    info.changeLifeBy(-3)
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite, otherSprite) {
    mySprite2.destroy(effects.fire, 500)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
})
let mySprite2: Sprite = null
let current_level = 0
scene.setBackgroundColor(7)
game.splash("find a wepin")
scene.cameraShake(4, 500)
current_level += 1
if (current_level == 1) {
    tiles.setTilemap(tilemap`level1`)
} else if (current_level == 2) {
	
} else {
    game.over(true)
}
let mySprite = sprites.create(img`
    ........................
    ........................
    .......ff...............
    .....ff22ff.............
    ...fff2222fff...........
    ..fff222222fff..........
    ..fff222222fff..........
    ..feeeeeeeeeeff.........
    .ffe22222222eff.........
    .fffffeeeefffff.........
    fdfefbf44fbfeff.........
    fbfe41fddf14ef..........
    fbffe4dddd4efe..........
    fcfef22222f4e...........
    .ff4f44554f4e...........
    ....ffffffdde...........
    .....ffffedde...........
    ..........ee............
    .........ccc............
    ........cc1cc...........
    .........c1c............
    .........c1c............
    .........c1c............
    .........c1c............
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
scene.cameraFollowSprite(mySprite)
mySprite2 = sprites.create(img`
    ................
    .......ddd......
    ......dbbb......
    ......dbdd......
    ......bddd......
    ......bcdbd.....
    ......cbcbdd....
    ......bdbdbd....
    .....cbdbdcd....
    .....cbbbddb....
    .....cfbdbdd....
    ....bcfbddbd....
    ....bcfdddd.....
    ....bfbdddd.....
    ...bbfdddddb....
    ...dcbdddddd....
    .....bdddddd....
    .....bddbddd....
    .....bddbdddb...
    .ccccbddbddddcc.
    cdddbbdbbddddbdc
    bddbdbdbbddbdbdb
    bddbdddbbddbbbdb
    bdddbddbbddbbddb
    bddddbbbbbbbbddb
    bdddddbbbbbddddb
    cddddddddddddddc
    bccddddddddddccb
    dbbbbbbbbbbbbbbd
    dbbbbccccccbbbbd
    cbbbbbbbbbbbbbbc
    fccccccccccccccf
    `, SpriteKind.Enemy)
tiles.placeOnRandomTile(mySprite2, sprites.castle.tilePath5)
mySprite2.follow(mySprite, 30)
let myEnemy = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
tiles.placeOnRandomTile(myEnemy, sprites.castle.saplingPine)
myEnemy.follow(mySprite, 30)
forever(function () {
    music.playMelody("C5 B F C5 B A G A ", 120)
    music.playMelody("E B C5 A B G A F ", 120)
})
